### ISSUE TITLE
Observation windows shouldn't depend on changepoints

### ISSUE THREAD

**Issue by sjbonner** [pmahon3/USRA2019#3]
The start and end of the observation windows in the simulaion shouldn't depend on the changepoints since these can't be known in a real data set.

**Comment by pmahon3** [comment]
Is this for the data simulation?

**Comment by sjbonner** [comment]
Yes. This strategy makes sense if you know where the changepoints are -- which you do in the data simulation -- but you couldn't know this with real data. This means that the the number of observations on either side of the changepoints will vary from day-to-day.  It's best to make the simulations as realistic as possible.

**Comment by pmahon3** [comment]
Ok, I think we originally decided to do a simulation window around the changepoint to reduce the number of data points for the MCMC and decrease simulaiton time. We can bring it back up to the full day but I think it's going to be exorbitantly long for simulations of an entire population on a standard machine.

**Comment by sjbonner** [comment]
We definitely don't want to use the full day, but we also don't want the window to depend on the exact changepoint. Instead, the user should choose a fixed window a priori. E.g., if he/she thinks that the changepoints 6:00am and 6:00pm then we should have windows from 5:00-7:00 both morning and evening with the same window for all individuals. Does that make sense?

**Comment by pmahon3** [comment]
Ok cool that makes sense!
