### ISSUE TITLE
Parameters of signal strength distribution should vary by day ( and other parameter variation questions )

### ISSUE THREAD

**Issue by sjbonner** [pmahon3/USRA2019#4]
Data simulation and model currently assume that the mean and variance of the signal strength are identical in the three periods for each day. We should allow these to vary according to some distribution.

**Comment by pmahon3** [comment]
Sounds good, I adopted the debug stategy of trying to extend the minimal variation required to cover delta.prime.

**Comment by pmahon3** [comment]
@sjbonner piggybacking this issue for the more general question of: how much variation is the right amount?

I've extended some minimal variation to the [Population level model](https://github.com/pmahon3/UWO-MOTUS-Analysis/blob/master/src/main/R/Population/v1.1/Model.R) from the validated [individual model](https://github.com/pmahon3/UWO-MOTUS-Analysis/blob/master/src/main/R/Individual/v1.1/Model.R)

I'm debating how much variation to add and how much is too much. I think varying signal strength by bird by day is realistic, however should we vary the variance parameters for the signal strength by bird by day? I have similar concerns about varying the variance parameters of individual bird properties that already vary per bird, per day. 

Is it ok for hyperparameters to grow exponentially as 2^n for normal distributions which take two arguments?

**Comment by pmahon3** [comment]
Regarding variation of signal strength by day, could there be further variation on [this hyperparameter](https://github.com/pmahon3/UWO-MOTUS-Analysis/blob/4d48d20b112b682b881c543ec826e75336a5fb68/src/main/R/Population/v1.1/Model.R#L58) with respect to [this distribution](https://github.com/pmahon3/UWO-MOTUS-Analysis/blob/4d48d20b112b682b881c543ec826e75336a5fb68/src/main/R/Population/v1.1/Model.R#L66), although I don't know if it's desirable or not. Right now the mean signal strength, `muY[i,j,p]` varies per bird per day, but the means from which it is derived, `muMuY[p]` does not vary per bird. Is this something we want to include or would that be too much? You can see proposed changes [here](https://github.com/pmahon3/UWO-MOTUS-Analysis/pull/6/files)

**Comment by pmahon3** [comment]
this is done here https://github.com/pmahon3/UWO-MOTUS-Analysis/commit/297681fcee9292d5526ffaef3982b5d40a86a0d2
